package de.dini.oanetzwerk.codec;

public enum RestKeyword {
	UNKNOWN,
	ObjectEntry,
	ObjectEntryID,
	AllOIDs,
	RawRecordData,
	InternalMetadataEntry,
	CompleteMetadataEntry,	
	Services,
	WorkflowDB,
	Repository,
	FullTextLinks,
	ObjectServiceStatus,
	ServiceNotifier,
	ServiceJob,
	LoginData,
	DDCCategories,
	DuplicateProbabilities,
	OAIExportCache,
	UnneededData,
	InterpolatedDDC,
	UsageData,
	UsageStatistics,
	DDCEntry,
	DDCStatistics,
	LanguageEntry,
	Statistics
}
