//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 11:04:52 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://purl.org/dc/elements/1.1/")
package org.purl.dc.elements._1;
