INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('03','Nachschlagewerke, Bibliographien')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('04','Adressbücher, Telefonbücher')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('05','Kalender')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('06','Publizistik')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('07','Kinder- und Jugendliteratur')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('08','Comics, Cartoons, Karikaturen')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('09','Grenzgebiete der Wissenschaft und Esoterik')
INSERT INTO DNB_Categories (DNB_Categorie, name) VALUES ('10','Philosophie')