//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.12.04 at 11:04:52 AM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openarchives.oai._2_0.oai_dc;
