insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('000', 'Allgemeines, Wissenschaft', 'Generalities, Science');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('004', 'Informatik', 'Data processing, Computer science');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('010', 'Bibliografien', 'Bibliography');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('020', 'Bibliotheks- und Informationswissenschaft', 'Library & information sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('030', 'Enzyklopädien', 'General encyclopedic works');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('050', 'Zeitschriften, fortlaufende Sammelwerke', 'General serials & their indexes');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('060', 'Organisationen, Museumswissenschaft', 'General organization & museology');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('070', 'Geografie, Reisen', 'News media, journalism, publishing');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('080', 'Allgemeine Sammelwerke', 'General collections');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('090', 'Handschriften, seltene Bücher', 'Manuscripts & rare books');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('100', 'Philosophie', 'Philosophy');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('130', 'Parapsychologie, Okkultismus', 'Paranormal phenomena');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('150', 'Psychologie', 'Psychology');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('200', 'Religion, Religionsphilosophie', 'Religion');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('220', 'Bibel', 'Bible');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('230', 'Theologie, Christentum', 'Christian theology');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('290', 'Andere Religionen', 'Other & comparative religions');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('300', 'Sozialwissenschaften, Soziologie', 'Social sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('310', 'Statistik', 'General statistics');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('320', 'Politik', 'Political science');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('330', 'Wirtschaft', 'Economics');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('333.7', 'Natürliche Ressourcen, Energie, Umwelt', 'Natural ressources, energy and environment');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('340', 'Recht', 'Law');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('350', 'Öffentliche Verwaltung', 'Public administration');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('355', 'Militär', 'Military science');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('360', 'Soziale Probleme, Sozialarbeit', 'Social services, association');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('370', 'Erziehung, Schul- und Bildungswesen', 'Education');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('380', 'Handel, Kommunikation, Verkehr', 'Commerce, communications, transport');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('390', 'Ethnologie', 'Customs, etiquette, folklore');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('400', 'Sprachwissenschaft, Linguistik', 'Language, Linguistics');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('420', 'Englisch', 'English');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('430', 'Deutsch', 'Germanic');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('439', 'Andere germanische Sprachen', 'Other Germanic languages');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('440', 'Französisch, romanische Sprachen allgemein', 'Romance languages, French');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('450', 'Italienisch, Rumänisch, Rätoromanisch', 'Italian, Romanian, Rhaeto-Romanic');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('460', 'Spanisch, Portugiesisch', 'Spanish & Portugese languages');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('470', 'Latein', 'Italic Latin');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('480', 'Griechisch', 'Hellenic languages, Classical Greek');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('490', 'Andere Sprachen', 'Other languages');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('500', 'Naturwissenschaften', 'Natural sciences & mathematics');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('510', 'Mathematik', 'Mathematics');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('520', 'Astronomie', 'Astronomy & allied sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('530', 'Physik', 'Physics');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('540', 'Chemie', 'Chemistry & allied sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('550', 'Geowissenschaften', 'Earth sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('560', 'Paläontologie', 'Paleontology, Paleozoology');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('570', 'Biowissenschaften, Biologie', 'Life sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('580', 'Pflanzen (Botanik)', 'Botanical sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('590', 'Tiere (Zoologie)', 'Zoological sciences');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('600', 'Technik', 'Technology (Applied sciences)');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('610', 'Medizin', 'Medical sciences Medicine');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('620', 'Ingenieurwissenschaften', 'Engineering & allied operations');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('630', 'Landwirtschaft, Veterinärmedizin', 'Agriculture');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('640', 'Hauswirtschaft', 'Home economics & family living');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('650', 'Management', 'Management & auxiliary services');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('660', 'Technische Chemie', 'Chemical engineering');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('670', 'Industrielle Fertigung', 'Manufacturing');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('690', 'Hausbau, Bauhandwerk', 'Buildings');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('700', 'Künste, Bildende Kunst allgemein', 'The arts');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('710', 'Landschaftsgestaltung, Raumplanung', 'Civic & landscape art');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('720', 'Architektur', 'Architecture');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('730', 'Plastik, Numismatik, Keramik, Metallkunst', 'Plastic arts, Sculpture');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('740', 'Zeichnung, Kunsthandwerk', 'Drawing & decorative arts');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('741.5', 'Comics, Cartoons, Karikaturen', 'Comics, Cartoons');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('750', 'Malerei', 'Painting & paintings');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('760', 'Grafische Verfahren, Drucke', 'Graphic arts Printmaking & prints');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('770', 'Fotografie, Computerkunst', 'Photography & photographs');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('780', 'Musik', 'Music');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('790', 'Freizeitgestaltung, Darstellende Kunst', 'Recreational & performing arts');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('791', 'Öffentliche Darbietungen, Film, Rundfunk', 'Public performances');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('792', 'Theater, Tanz', 'Stage presentations');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('793', 'Spiel', 'Indoor games & amusements');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('796', 'Sport', 'Athletic & outdoor sports & games');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('800', 'Literatur, Rhetorik, Literaturwissenschaft', 'Literature & rhetoric');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('810', 'Englische Literatur Amerikas', 'American literature in English');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('820', 'Englische Literatur', 'English & Old English literatures');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('830', 'Deutsche Literatur', 'Literatures of Germanic languages');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('839', 'Literatur in anderen germanischen Sprachen', 'Other Germanic literatures');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('840', 'Französische Literatur', 'Literatures of Romance languages');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('850', 'Italienische, rumänische, rätoromanische Literatur', 'Italian, Romanian, Rhaeto-Romanic literatures');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('860', 'Spanische und portugiesische Literatur', 'Spanish & Portuguese literatures');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('870', 'Lateinische Literatur', 'Italic literatures, Latin');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('880', 'Griechische Literatur', 'Hellenic literatures Classical Greek');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('890', 'Literatur in anderen Sprachen', 'Literatures of other languages');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('900', 'Geschichte', 'Geography & history');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('910', 'Geografie, Reisen', 'Geography & travel');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('914.3', 'Landeskunde Deutschlands', 'Geography & travel Germany');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('920', 'Biografie, Genealogie, Heraldik', 'Biography, genealogy, insignia');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('930', 'Alte Geschichte, Archäologie', 'History of the ancient world');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('940', 'Geschichte Europas', 'General history of Europe');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('943', 'Geschichte Deutschlands', 'General history of Europe, Central Europe, Germany');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('950', 'Geschichte Asiens', 'General history of Asia Far East');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('960', 'Geschichte Afrikas', 'General history of Africa');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('970', 'Geschichte Nordamerikas', 'General history of North America');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('980', 'Geschichte Südamerikas', 'General history of South America');
insert into "DDC_Categories" ("DDC_Categorie", name, name_en) values ('990', 'Geschichte der übrigen Welt', 'General history of other areas');



insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (1, 'pub-type:monograph', 'Books, Monographs', 'Bücher, Monographien');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (2, 'pub-type:article', 'Journal Articles', 'Zeitschriftenartikel');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (3, 'pub-type:dissertation', 'Dissertations and Professional Dissertations', 'Dissertationen und Habilitationen');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (4, 'pub-type:masterthesis', 'Diploma Theses', 'Diplomarbeiten');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (5, 'pub-type:report', 'Reports', 'Berichte');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (6, 'pub-type:paper', 'Papers', 'Papers');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (7, 'pub-type:conf-proceeding', 'Conference Proceedings', 'Tagungs- und Konferenzbeiträge');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (8, 'pub-type:lecture', 'Lectures', 'Vorlesungen');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (9, 'pub-type:music', 'Music', 'Musik');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (10, 'pub-type:program', 'Programs / Software', 'Programme / Software');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (11, 'pub-type:play', 'Plays', 'Schauspiele / Theaterstücke');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (12, 'pub-type:news', 'News', 'Nachrichten');
insert into "DINI_Set_Categories" ("DINI_set_id", name, "setNameEng", "setNameDeu") values (13, 'pub-type:standards', 'Standards', 'Standards');


insert into "DNB_Categories" ("DNB_Categorie", name) values ('01', 'Wissenschaft und Kultur allgemein');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('02', 'Schrift, Buch, Bibliothek, Information und Dokumentation');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('03', 'Nachschlagewerke, Bibliographien');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('04', 'Adressbücher, Telefonbücher');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('05', 'Kalender');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('06', 'Publizistik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('07', 'Kinder- und Jugendliteratur');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('08', 'Comics, Cartoons, Karikaturen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('09', 'Grenzgebiete der Wissenschaft und Esoterik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('10', 'Philosophie');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('11', 'Psychologie');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('12', 'Christliche Religion');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('13', 'Allgemeine und Vergleichende Religionswissenschaft, Nichtchristliche Religionen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('14', 'Soziologie, Gesellschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('15', 'Statistik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('16', 'Politik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('17', 'Wirtschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('18', 'Arbeit');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('19', 'Recht');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('20', 'Öffentliche Verwaltung');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('21', 'Militär');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('22', 'Erziehung, Bildung, Unterricht');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('23', 'Schulbücher');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('24', 'Berufsschulbücher');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('25', 'Volkskunde, Völkerkunde');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('26', 'Natur, Naturwissenschaften allgemein');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('27', 'Mathematik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('28', 'Informatik, Datenverarbeitung');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('29', 'Physik, Astronomie');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('30', 'Chemie');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('31', 'Geowissenschaften');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('32', 'Biologie');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('33', 'Medizin');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('34', 'Tiermedizin');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('35', 'Technik allgemein');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('36', 'Energie-, Maschinen-, Fertigungstechnik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('37', 'Elektrotechnik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('38', 'Bergbau, Bautechnik, Umwelttechnik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('39', 'Landwirtschaft, Garten');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('40', 'Hauswirtschaft, Kochen, Hotel-und Gaststättengewerbe');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('41', 'Nachrichten- und Verkehrswesen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('42', 'Technische Chemie, Lebensmitteltechnologie, Textiltechnik und andere Technologien');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('43', 'Basteln, Handarbeiten, Heimwerken');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('44', 'Umweltschutz, Raumordnung, Landschaftsgestaltung');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('45', 'Architektur');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('46', 'Bildende Kunst');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('47', 'Photographie');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('48', 'Musik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('49', 'Theater, Tanz, Film');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('50', 'Sport, Spiele');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('51', 'Allgemeine und Vergleichende Sprach- und Literaturwissenschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('52', 'Englische Sprach- und Literaturwissenschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('53', 'Deutsche Sprach- und Literaturwissenschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('54', 'Sprach- und Literaturwissenschaft der übrigen germanischen Sprachen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('55', 'Romanische Sprach- und Literaturwissenschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('56', 'Klassische Sprach- und Literaturwissenschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('57', 'Slawische und baltische Sprach- und Literaturwissenschaft');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('58', 'Sprach- und Literaturwissenschaft sonstiger Sprachen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('59', 'Belletristik');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('60', 'Archäologie, Vor- und Frühgeschichte');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('61', 'Geographie, Heimat- und Länderkunde, Reisen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('62', 'Atlanten');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('63', 'Geschichte und Historische Hilfswissenschaften');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('64', 'Sozialgeschichte');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('65', 'Wirtschaftsgeschichte');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('78', 'Abgeschlossene Veröffentlichungen');
insert into "DNB_Categories" ("DNB_Categorie", name) values ('79', 'Berichtigungen');



insert into "Iso639Language" (language_id, "iso639language") values (1, 'deu');
insert into "Iso639Language" (language_id, "iso639language") values (2, 'eng');
insert into "Iso639Language" (language_id, "iso639language") values (3, 'fra');
insert into "Iso639Language" (language_id, "iso639language") values (4, 'mis');
insert into "Iso639Language" (language_id, "iso639language") values (5, 'spa');
insert into "Iso639Language" (language_id, "iso639language") values (6, 'ita');
insert into "Iso639Language" (language_id, "iso639language") values (7, 'mul');
insert into "Iso639Language" (language_id, "iso639language") values (8, 'lat');
insert into "Iso639Language" (language_id, "iso639language") values (9, 'rus');
insert into "Iso639Language" (language_id, "iso639language") values (10, 'pol');
insert into "Iso639Language" (language_id, "iso639language") values (11, 'swe');
insert into "Iso639Language" (language_id, "iso639language") values (12, 'und');
insert into "Iso639Language" (language_id, "iso639language") values (13, 'por');
insert into "Iso639Language" (language_id, "iso639language") values (14, 'jpn');
insert into "Iso639Language" (language_id, "iso639language") values (15, 'ara');
insert into "Iso639Language" (language_id, "iso639language") values (16, 'ben');
insert into "Iso639Language" (language_id, "iso639language") values (17, 'ell');
insert into "Iso639Language" (language_id, "iso639language") values (18, 'hun');
insert into "Iso639Language" (language_id, "iso639language") values (19, 'ces');
insert into "Iso639Language" (language_id, "iso639language") values (20, 'dan');



INSERT INTO "public"."Repositories" VALUES ('1', 'EDOC HU', 'http://edoc.hu-berlin.de', 'http://edoc.hu-berlin.de/OAI-2.0', 't', '10', '5000', '2010-07-16 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('2', 'RWTH Aachen', 'http://www.bth.rwth-aachen.de/opus3', 'http://darwin.bth.rwth-aachen.de/opus3/oai2/oai2.php', 't', '10', '5000', '2010-07-16 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('3', 'Fraunhofer Eprints', 'http://eprints.fraunhofer.de', 'http://publica.fraunhofer.de/eprints.har', 't', '10', '5000', '2010-07-16 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('4', 'MONARCH Chemnitz', 'http://archiv.tu-chemnitz.de', 'http://archiv.tu-chemnitz.de/cgi-bin/interfaces/oai/oai2.pl', 't', '10', '5000', '2010-07-16 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('5', 'ART DOK Heidelberg', 'http://archiv.ub.uni-heidelberg.de/artdok', 'http://archiv.ub.uni-heidelberg.de/artdok/oai2/oai2.php', 't', '10', '5000', '2010-07-16 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('6', 'Propylaeum DOK Heidelberg', 'http://archiv.ub.uni-heidelberg.de/propylaeumdok', 'http://archiv.ub.uni-heidelberg.de/propylaeumdok/oai2/oai2.php', 't', '10', '5000', '2010-07-14 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('7', 'Savifa DOK Heidelberg', 'http://archiv.ub.uni-heidelberg.de/savifadok', 'http://archiv.ub.uni-heidelberg.de/savifadok/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('8', 'Universität Potsdam', 'http://pub.ub.uni-potsdam.de', 'http://opus.kobv.de/ubp/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('9', 'BieSon Bielefeld', 'http://bieson.ub.uni-bielefeld.de/index.php', 'http://bieson.ub.uni-bielefeld.de/phpoai/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('10', 'TUBdok TU Hamburg-Harbug', 'http://doku.b.tu-harburg.de', 'http://doku.b.tu-harburg.de/oai/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('11', 'Universität Bremen', 'http://elib.suub.uni-bremen.de', 'http://elib.suub.uni-bremen.de/cgi-bin/oai2', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('12', 'KOPS Konstanz', 'http://www.ub.uni-konstanz.de/kops', 'http://www.ub.uni-konstanz.de/kops/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('13', 'KOBRA Kasseler Online Bibliothek', 'https://kobra.bibliothek.uni-kassel.de', 'http://oai.bibliothek.uni-kassel.de/dspace-oai/request', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('14', 'Webdoc Göttingen', 'http://webdoc.sub.gwdg.de', 'http://www.gbv.de/goai/gbvrep.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('15', 'ask23, Hochschule für bildende Kunst Hamburg', 'http://ask23.hfbk-hamburg.de', 'http://purl.oclc.org/NET/ugent/lib/srepod/oai.ask23.de/static/ask23-oai.xml', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('16', 'HSSS Dresden', 'http://hsss.slub-dresden.de', 'http://hsss.slub-dresden.de/oai/OAI-2.0', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('17', 'MADOC Mannheim', 'http://madoc.bib.uni-mannheim.de/madoc', 'http://madoc.bib.uni-mannheim.de/madoc/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('18', 'ArchiMeD Mainz', 'http://archimed.uni-mainz.de', 'http://ubm.opus.hbz-nrw.de/phpoai/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('19', 'HeiDOK', 'http://archiv.ub.uni-heidelberg.de', 'http://archiv.ub.uni-heidelberg.de/propylaeumdok/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('20', 'SciDOK Saarbruecken', 'http://scidok.sulb.uni-saarland.de', 'http://scidok.sulb.uni-saarland.de/phpoai/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('21', 'PsyDok Saarbruecken', 'http://psydok.sulb.uni-saarland.de', 'http://psydok.sulb.uni-saarland.de/phpoai/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('22', 'OPUS Stuttgart', 'http://elib.uni-stuttgart.de/opus', 'http://elib.uni-stuttgart.de/opus/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-21 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('23', 'TOBIAS-lib Tuebingen', 'http://tobias-lib.uni-tuebingen.de', 'http://tobias-lib.uni-tuebingen.de/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('24', 'OPUS Hohenheim', 'http://www.ub.uni-hohenheim.de/opus/index.html', 'http://opus.ub.uni-hohenheim.de/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('25', 'Volltextserver Ulm', 'http://vts.uni-ulm.de', 'http://vts.uni-ulm.de/oai/oai.asp', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('26', 'SerWisS - Fachhochschule Hannover', 'http://opus.bsz-bw.de/fhhv', 'http://opus.bsz-bw.de/fhhv/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('27', 'EVA STAR - Uni Karlsruhe', 'http://www.ubka.uni-karlsruhe.de/eva/index.html', 'http://www.ubka.uni-karlsruhe.de/oai/eva/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('28', 'DuEPublico Duisbug-Essen', 'http://duepublico.uni-duisburg-essen.de/', 'http://duepublico.uni-duisburg-essen.de/servlets/OAIDataProvider', 't', '10', '5000', null, 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('29', 'Robert Koch-Institut', 'http://edoc.rki.de/', 'http://edoc.rki.de/OAI', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('30', 'Europauniversitaet Viadrina Frankfurt/Oder', 'http://www.euv-frankfurt-o.de', 'http://opus.kobv.de/euv/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-06-03 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('31', 'Qucosa', 'http://www.qucosa.de/', 'http://www.qucosa.de/oai/', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('32', 'SSOAR - Social Science Open Access Repository', 'http://www.ssoar.info/', 'http://www.ssoar.info/ssoar/OAIHandler', 't', '10', '5000', '2010-07-15 00:00:00', 'f', null, 't');
INSERT INTO "public"."Repositories" VALUES ('33', 'Digitale Bibliothek Thüringen', 'http://www.db-thueringen.de/', 'http://www.db-thueringen.de/servlets/OAIDataProvider', 't', '10', '5000', '2010-07-16 00:00:00', 'f', '2010-07-22 00:00:00', 't');
INSERT INTO "public"."Repositories" VALUES ('34', 'Digitales Repositorium der TU Berlin', 'http://opus.kobv.de/tuberlin/', 'http://opus.kobv.de/tuberlin/oai2/oai2.php', 't', '10', '5000', '2010-07-15 00:00:00', 'f', '2010-07-22 00:00:00', 't');


insert into "Repository_Sets" (name, repository_id) values ('DB_THUERINGEN', 33);
insert into "Repository_Sets" (name, repository_id) values ('DUISBURG_ESSEN_DUEPUBLICO', 28);
insert into "Repository_Sets" (name, repository_id) values ('EUROPA_UNI_VIADRINA_FRANKFURT', 30);
insert into "Repository_Sets" (name, repository_id) values ('FH_HANNOVER_SERWISS', 26);
insert into "Repository_Sets" (name, repository_id) values ('FRAUNHOFER_EPRINTS', 3);
insert into "Repository_Sets" (name, repository_id) values ('HBK_HAMBURG_ASK23', 15);
insert into "Repository_Sets" (name, repository_id) values ('HSSS_DRESDEN', 16);
insert into "Repository_Sets" (name, repository_id) values ('HU_BERLIN_EDOC', 1);
insert into "Repository_Sets" (name, repository_id) values ('KASSELER_OB_KOBRA', 13);
insert into "Repository_Sets" (name, repository_id) values ('QUCOSA', 31);
insert into "Repository_Sets" (name, repository_id) values ('RKI', 29);
insert into "Repository_Sets" (name, repository_id) values ('RWTH_AACHEN', 2);
insert into "Repository_Sets" (name, repository_id) values ('SSOAR', 32);
insert into "Repository_Sets" (name, repository_id) values ('SUB_GOETTINGEN_WEBDOC', 14);
insert into "Repository_Sets" (name, repository_id) values ('TU_BERLIN_DR', 34);
insert into "Repository_Sets" (name, repository_id) values ('TU_CHEMNITZ_MONARCH', 4);
insert into "Repository_Sets" (name, repository_id) values ('TU_HAMBURG_HARBURG_TUBDOK', 10);
insert into "Repository_Sets" (name, repository_id) values ('UNI_BIELEFELD_BIESON', 9);
insert into "Repository_Sets" (name, repository_id) values ('UNI_BREMEN', 11);
insert into "Repository_Sets" (name, repository_id) values ('UNI_HEIDELBERG_ART_DOK', 5);
insert into "Repository_Sets" (name, repository_id) values ('UNI_HEIDELBERG_HEIDOK', 19);
insert into "Repository_Sets" (name, repository_id) values ('UNI_HEIDELBERG_PROPYLAEUM_DOK', 6);
insert into "Repository_Sets" (name, repository_id) values ('UNI_HEIDELBERG_SAVIFA_DOK', 7);
insert into "Repository_Sets" (name, repository_id) values ('UNI_HOHENHEIM_OPUS', 24);
insert into "Repository_Sets" (name, repository_id) values ('UNI_KARLSRUHE_EVASTAR', 27);
insert into "Repository_Sets" (name, repository_id) values ('UNI_KONSTANZ_KOPS', 12);
insert into "Repository_Sets" (name, repository_id) values ('UNI_MAINZ_ARCHIMED', 18);
insert into "Repository_Sets" (name, repository_id) values ('UNI_MANNHEIM_MADOC', 17);
insert into "Repository_Sets" (name, repository_id) values ('UNI_POTSDAM', 8);
insert into "Repository_Sets" (name, repository_id) values ('UNI_SAARBRUECKEN_PSYDOK', 21);
insert into "Repository_Sets" (name, repository_id) values ('UNI_SAARBRUECKEN_SCIDOK', 20);
insert into "Repository_Sets" (name, repository_id) values ('UNI_STUTTGART_OPUS', 22);
insert into "Repository_Sets" (name, repository_id) values ('UNI_TUEBINGEN_TOBIASLIB', 23);
insert into "Repository_Sets" (name, repository_id) values ('UNI_ULM_VTS', 25);



insert INTO "Services" (service_id, name) values (1, 'Harvester');
insert INTO "Services" (service_id, name) values (2, 'Aggregator');
insert INTO "Services" (service_id, name) values (3, 'MarkAndErase');
insert INTO "Services" (service_id, name) values (4, 'Fulltextlink');
insert INTO "Services" (service_id, name) values (5, 'OCR');
insert INTO "Services" (service_id, name) values (6, 'LanguageDetection');
insert INTO "Services" (service_id, name) values (7, 'Classifier');
insert INTO "Services" (service_id, name) values (8, 'DuplicateCheck');


insert INTO "ServicesOrder" (service_id, predecessor_id) values (1, null);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (2, 1);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (3, 2);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (4, 3);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (5, 4);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (6, 5);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (7, 6);
insert INTO "ServicesOrder" (service_id, predecessor_id) values (8, 7);


insert into "UsageData_Metrics" (metrics_id, name) values (1, 'Logec');
insert into "UsageData_Metrics" (metrics_id, name) values (2, 'Counter');
insert into "UsageData_Metrics" (metrics_id, name) values (3, 'IFABC');

