package de.dini.oanetzwerk.servicemodule.aggregator;

import java.io.StringReader;
import java.io.StringWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;

import org.junit.BeforeClass;
import org.junit.Test;

import de.dini.oanetzwerk.utils.imf.DDCClassification;
import de.dini.oanetzwerk.utils.imf.DINISetClassification;
import de.dini.oanetzwerk.utils.imf.DNBClassification;
import de.dini.oanetzwerk.utils.imf.InternalMetadata;
import de.dini.oanetzwerk.utils.imf.OtherClassification;

public class TestAggregator {

	public static JAXBContext context;
	
	public static final String TEST_RECORD = 
	   "<oai_dc:dc\n" + 
       "     xmlns:oai_dc=\"http://www.openarchives.org/OAI/2.0/oai_dc/\"\n" + 
       "     xmlns:dc=\"http://purl.org/dc/elements/1.1/\"\n" +  
       "     xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n" +  
       "     xsi:schemaLocation=\"http://www.openarchives.org/OAI/2.0/oai_dc/\n" + 
       "     http://www.openarchives.org/OAI/2.0/oai_dc.xsd\">\n" +

       "  <dc:title>1st title element</dc:title>\n" +
       "  <dc:title>2nd title element</dc:title>\n" +
       "  <dc:title>3rd title element</dc:title>\n" +
       "  <dc:title>4th title element</dc:title>\n" +
       "  <dc:title>5th title element</dc:title>\n" +

       "  <dc:creator>VornameVorne NachnameHinten</dc:creator>\n" +
       "  <dc:creator>VornameVorne   NachnameHinten</dc:creator>\n" +
       "  <dc:creator>VornameVorne\tNachnameHinten</dc:creator>\n" +
       "  <dc:creator>VornameVorne\nNachnameHinten</dc:creator>\n" +
       "  <dc:creator>NachnameVorne, VornameHinten</dc:creator>\n" +
       "  <dc:creator>NachnameVorne,VornameHintenOhneLeerzeichen</dc:creator>\n" +
       "  <dc:creator>Vorname1Vorne-Vorname2Vorne NachnameHinten</dc:creator>\n" +
       "  <dc:creator>VornameVorne Nachname1Hinten-Nachname2Hinten</dc:creator>\n" +
       "  <dc:creator>NurEinName</dc:creator>\n" +
       "  <dc:creator>A. B. NameMitKuerzel</dc:creator>\n" +
       "  <dc:creator>A.B.KuerzelLeerzeichenFehlt</dc:creator>\n" +

       "  <dc:subject>Mathematik</dc:subject>\n" +
       "  <dc:subject>Brownsche Bewegung</dc:subject>\n" +
       "  <dc:subject>Brownsche Filtrierung</dc:subject>\n" +
       "  <dc:subject>Insiderhandel</dc:subject>\n" +
       "  <dc:subject>Stochastische Filtering Theorie.</dc:subject>\n" + 
       "  <dc:subject>Brownian motion</dc:subject>\n" +
       "  <dc:subject>Brownian filtration</dc:subject>\n" +
       "  <dc:subject>insider trading</dc:subject>\n" +
       "  <dc:subject>stochastic filtering theory</dc:subject>\n" +
       "  <dc:subject>Mathematik</dc:subject>\n" +
       "  <dc:subject>SK 820</dc:subject>\n" +
       "  <dc:description>In dieser Arbeit untersuchen wir die Struktur von Gausschen Prozessen, die durch gewisse lineare Transformationen von zwei Gausschen Martingalen erzeugt werden. Die Klasse dieser Transformationen ist durch nanzmathematische Gleichgewichtsmodelle mit heterogener Information motiviert.     In Kapital 2 bestimmen wir für solche Prozesse, die zunächst in einer erweiterten Filtrierung konstruiert werden, die kanonische Zerlegung als Semimartin-gale in ihrer eigenen Filtrierung. Die resultierende Drift wird durch Volterra-Kerne beschrieben. Insbesondere charakterisieren wir diejenigen Prozesse, die in ihrer eigenen Filtrierung eine Brownsche Bewegung bilden. In Kapital 3 konstruieren wir neue orthogonale Zerlegungen der Brownschen Filtrierungen.  In den Kapitaln 4 bis 6 wenden wir unsere Resultate zur Charakterisierung Brownscher Bewegungen im Kontext nanzmathematischer Modelle an, in denen es Marktteilnehmer mit zusätzlicher Insider-Information gibt. Wir untersuchen Erweiterungen eines Gleichgewichtsmodells von Kyle [42] und Back [7], in denen die Insider-Information in verschiedener Weise durch Gaussche Martingale spezifiziert wird. Insbesondere klären wir die Struktur von Insider-Strategien, die insofern unaufallig bleiben, als sich die resultierende Gesamtnachfrage wie eine Brownsche Bewegung verhält.</dc:description>\n" +
       "  <dc:description>In this thesis, we study Gaussian processes generated by certain linear transformations of two Gaussian martingales. This class of transformations is motivated by  nancial equilibrium models with heterogeneous information. In Chapter 2 we derive the canonical decomposition of such processes, which are constructed in an enlarged ltration, as semimartingales in their own ltration. The resulting drift is described in terms of Volterra kernels. In particular we characterize  those processes which are Brownian motions in their own ltration. In Chapter 3 we construct new orthogonal decompositions of Brownian ltrations.   In Chapters 4 to 6 we are concerned with applications of our characterization results in the context of mathematical models of insider trading. We analyze extensions of the nancial equilibrium model of Kyle [42] and Back [7] where the Gaussian martingale describing the insider information is specified in various ways. In particular we discuss the structure of insider strategies which remain inconspicuous in the sense that the resulting cumulative demand is again a Brownian motion.</dc:description>\n" +
       "  <dc:publisher>Mathematisch-Naturwissenschaftliche Fakultät II</dc:publisher>\n" +
       "  <dc:date>1999-06-08</dc:date><dc:type>Text</dc:type><dc:type>dissertation</dc:type><dc:format>application/pdf</dc:format><dc:identifier>http://edoc.hu-berlin.de/dissertationen/mathe/wu-ching-tang/PDF/Wu.pdf</dc:identifier><dc:format>application/postscript</dc:format><dc:identifier>http://edoc.hu-berlin.de/dissertationen/mathe/wu-ching-tang/PS/Wu.ps</dc:identifier><dc:language>eng</dc:language>\n" +
       "</oai_dc:dc>\n";
	
	@BeforeClass
	public static void init() {
		try {
			context = JAXBContext.newInstance( InternalMetadata.class, OtherClassification.class, DINISetClassification.class, DNBClassification.class, DDCClassification.class ); 
		} catch(JAXBException jex) {
			System.err.println(jex);
		}
	}
	
	@Test
	public void testGenerateIMF() {		
		String strXML = TEST_RECORD;
		IMFGeneratorDCSimple imGen = new IMFGeneratorDCSimple();
		InternalMetadata myIM = imGen.generateIMF(strXML);
		System.out.println(myIM);
	}
		
	@Test
	public void test_IMF_marshalling() {
		
		InternalMetadata originalIM = InternalMetadata.createDummy();
	
		System.out.println("");
		System.out.println(originalIM);
		System.out.println("");
		
		StringWriter sw = new StringWriter();
		try {
			Marshaller m = context.createMarshaller(); 
			m.setEventHandler(new javax.xml.bind.helpers.DefaultValidationEventHandler());
			m.setProperty( Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE ); 
			m.setProperty( Marshaller.JAXB_FRAGMENT, Boolean.TRUE );
			m.marshal( originalIM, System.out );
			m.marshal( originalIM, sw);
		} catch(JAXBException jex) {
			System.err.println(jex);
		}

		try {
			Unmarshaller um = context.createUnmarshaller(); 
			um.setEventHandler(new javax.xml.bind.helpers.DefaultValidationEventHandler());
			//System.out.println(context.toString());
			InternalMetadata receivedIM = (InternalMetadata) um.unmarshal( new StringReader(sw.toString()) );
/*			InternalMetadata receivedIM = (InternalMetadata) um.unmarshal( new StringReader(
		    "<ns2:internalMetadata xmlns:ns2=\"http://oanetzwerk.dini.de/\">" +
			"<typeValueCounter>1</typeValueCounter>" +
		    "<typeValueList>" +
		    "    <number>1</number>" +
		    "    <typeValue>TypeValue</typeValue>" +
		    "</typeValueList>" +
		    "<classificationList>" +
	        "<otherClassification xsi:type=\"OtherClassification.class\">" +
	        "    <value>foo:bar</value>" +
	        "</otherClassification>" +
	        "<diniSetClassification>" +
	        "    <value>foo1</value>" +
	        "</diniSetClassification>" +
	        "<ddcClassification>" +
	        "    <value>foo2</value>" +
	        "</ddcClassification>" +
	        "<dnbClassification>" +
	        "    <value>foo3</value>" +
	        "</dnbClassification>" +
	        "</classificationList>" +
		    "</ns2:internalMetadata>" ));*/
			
			
			
			System.out.println("");
			System.out.println( receivedIM ); 
			System.out.println("");
		} catch(JAXBException jex) {
			System.err.println(jex);
		}

	}
	
}
